name: deploy-latest

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'view or server'
        required: true
      version:
        description: 'version'
        required: true
        default: 'latest'

jobs:
  view-deploy:
    if: github.event.inputs.target == 'view'
    runs-on: ubuntu-latest
    env:
      DOCKER_PATH : /usr/local/bin/docker
    steps:
    - name: connect ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          ${{ DOCKER_PATH }} pull ${{ secrets.DOCKERHUB_USERNAME }}/sample-front:${{ github.event.inputs.version }}
          ${{ DOCKER_PATH }} stop sample-front
          ${{ DOCKER_PATH }} rm sample-front
          ${{ DOCKER_PATH }} run -d -p 80:80 --name sample-front ${{ secrets.DOCKERHUB_USERNAME }}/sample-front:${{ github.event.inputs.version }}
