name: deploy-latest

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'view or server'
        required: true
      version:
        description: 'version'
        required: true
        default: 'latest'

jobs:
  view-deploy:
    if: github.event.inputs.target == 'view'
    runs-on: ubuntu-latest
    steps:
    - name: connect ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          /usr/local/bin/docker pull ${{ secrets.DOCKERHUB_USERNAME }}/sample-front:${{ github.event.inputs.version }}
          /usr/local/bin/docker stop sample-front
          /usr/local/bin/docker rm sample-front
          /usr/local/bin/docker run -d -p 80:80 --name sample-front ${{ secrets.DOCKERHUB_USERNAME }}/sample-front:${{ github.event.inputs.version }}
