name: build-on-tag-push

on:
  push:
    tags:
      - 'front-*'
      - 'back-*'

jobs:
  front-build:
    if: startsWith(github.ref, 'refs/tags/front-')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Build With Npm
        run: |
          npm install
          npm run build

  back-build:
    if: startsWith(github.ref, 'refs/tags/back-')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/sample
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.10.2

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Set Environment Variable
        run: |
          TAG=$(echo $GITHUB_REF | cut -d '/' -f 3 | cut -d '-' -f 2)
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "DOCKER_USER=${{ secrets.DOCKERHUB_USERNAME }}" >> $GITHUB_ENV
          echo "DOCKER_TOKEN=${{ secrets.DOCKERHUB_TOKEN }}" >> $GITHUB_ENV
          echo "DOCKER_IMAGE=sample-server:$TAG" >> $GITHUB_ENV

      - name: build docker image
        run: docker build -t $DOCKER_USER/$DOCKER_IMAGE .

      - name: Publish to docker hub
        run: |
          docker login -u $DOCKER_USER --password-stdin $DOCKER_TOKEN
          docker push $DOCKER_USER/$DOCKER_IMAGE
