name: build-on-tag-push

on:
  push:
    tags:
      - 'front-*'
      - 'back-*'

jobs:
  front-build:
    if: startsWith(github.ref, 'refs/tags/front-')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Build With Npm
        run: |
          npm install
          npm run build

  back-build:
    if: startsWith(github.ref, 'refs/tags/back-')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/sample
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.10.2

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Extract tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" | cut -d '-' -f 2 >> $GITHUB_ENV

      - name: build docker image
        run: |
          docker build -t photograph-server:$TAG .
