name: ci

on:
  push:
    branches:
      - master
    tags:
      - 'front-*'
      - 'back-*'
  pull_request:
    branches:
      - master

jobs:
  front-build:
    if: startsWith(github.ref, 'refs/tags/front-')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: change directory
        run: cd frontend
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build

  back-build:
    if: startsWith(github.ref, 'refs/tags/back-')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: change directory
        run: cd backend
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew build
